### ISSUE TITLE
User Login Requirements

### ISSUE THREAD

**Issue by rithik25** [Angelica-M/PriceCompare#4]
i.	 Upon clicking the Sign Up hyperlink, user gets redirected to the Sign Up page
ii.	 Text in the password field is hidden
iii.	 Create the necessary back-end functionalities so that user’s credentials are validated using Back4app. Upon authentication confirmation, user gets redirected to the View List page.

**Comment by SanCarlos25** [comment]
I have completed the Login Requirements.
